# Generated by Django 4.1.1 on 2022-09-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('new', 'pr-label1'), ('hot', 'pr-label2'), ('sale', 'on-sale')], max_length=4),
        ),
    ]
