# Generated by Django 4.1.1 on 2022-09-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[(0, 'Women'), (1, 'Men')], default='women', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('on-sale', 'new'), ('pr-label1', 'hot'), ('pr-label2', 'sale')], max_length=20),
        ),
    ]
